FROM smoosh

# :( things go out of date with Debian so quickly
RUN sudo apt-get install -y zlib1g-dev
RUN curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
RUN cat ~/.bashrc
RUN ~/.rbenv/bin/rbenv install 2.5.9 || cat /tmp/ruby-build.*
ENV PATH=/home/opam/.rbenv/versions/2.5.9/bin:$PATH
RUN ruby --version
RUN gem install ffi -v 1.9.10
RUN gem install -v 0.9.0 childprocess 
RUN gem install -v 2.0.5 sinatra
RUN gem install -v 2.0.5 sinatra-contrib
RUN gem install -v 1.7.2 thin
RUN gem update --system 3.2.3
RUN gem install -v 2.3.27 bundler

ADD --chown=opam:opam web web
RUN cd web; bundle install
RUN mv web/src/config.yml.docker web/src/config.yml
RUN mkdir web/submissions
VOLUME web/submissions

EXPOSE 2080/tcp
#EXPOSE 2443/tcp

HEALTHCHECK CMD curl --fail --data-ascii @web/test.post http://localhost:2080/shtepper

#ENTRYPOINT [ "opam", "config", "exec", "--" ]
CMD /home/opam/web/run.sh
